name: Build and generate preview, then comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    environment:
      name: preview
    steps:
      - name: Set preview URL
        run:
          echo "PREVIEW_URL=https://visitor-qa.komabasai.net/" >> "$GITHUB_ENV"

      - name: Comment PR with QA URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ github.event.pull_request.number }} --repo "$GITHUB_REPOSITORY" --body "## QAリンク

          以下の URL から [ウェブサイトQA](${PREVIEW_URL}) にアクセスできます。

          [${PREVIEW_URL}](${PREVIEW_URL})
          "

